### ISSUE TITLE
Save the Optimizer 

### ISSUE THREAD

**Issue by ahmed-fau** [deNsuh/segan-pytorch#14]
Hi @deNsuh ,

It seems that resuming the training process is incomplete as the optimizers for both generator and discriminator networks are not being saved. 

Best Regards

**Comment by dansuh17** [comment]
True. Saving the state of the optimizer will not be difficult. Are you willing to do a pull-request with this? If not, I'll be happy to implement this myself :)

**Comment by ahmed-fau** [comment]
Unfortunately I am still not proficient with Github utilities and edit the scripts locally :( 
Sorry for that and thanks for your support.

**Comment by dansuh17** [comment]
Sorry for the late work. Saving the optimizer states as well as model states are now implemented.
