### ISSUE TITLE
why your test data is in your train batch

### ISSUE THREAD

**Issue by ScarfBoy0903** [deNsuh/segan-pytorch#18]
thanks for you code, it helps me a lot, and there r some problems when training,
I found that your batch size is 200 and the original paper used 400, have you tried other batch size?
and your test data is in your train batch, is there any reason for doing this?
and why is the hyper-parameter of activation function used in discriminator is "negative_slope = 0.03" (different from original paper)

thank you

**Comment by dansuh17** [comment]
What do you mean by 'test data is in the train batch'? Could you refer the code you are mentioning?
Also, various hyperparameters that differ from the original paper might have been a result of my testing with various hyperparameter values. You are free to test them with different values yourself, as the values hardcoded here are not guaranteed to give the best results :)
