### ISSUE TITLE
The output of discriminator is [1 x 8]?

### ISSUE THREAD

**Issue by simpleoier** [deNsuh/segan-pytorch#3]
As a true or false indicator, shouldn't the output of discriminator be a scalar?

**Comment by dansuh17** [comment]
@simpleoier yes, I guess you're right. I think I was mistaken by 
> in the last activation layer thereis a one-dimensional convolution layer with one filter of width one that does not downsample the hidden activations (1 × 1 convolution).

in the paper.
But it seems clear from the [code](https://github.com/santi-pdp/segan/blob/master/discriminator.py#L80) that there is a fully connected layer required before the output of discriminator.

Thanks for commenting;
I'll put up a commit soon that fixes this :) (or you can open a pull request, if you don't mind)

**Comment by simpleoier** [comment]
Actually, in the paper
> The latter (3) reduces the amount of parameters re- quired for the final classification neuron, which is fully con- nected to all hidden activations with a linear behavior.

**Comment by dansuh17** [comment]
I'll keep this open until the fix has been made

**Comment by dansuh17** [comment]
Fix made with commit `26f2a8e`. closing.
